### ISSUE TITLE
Lollipop has a bug where SD cards are null.

### ISSUE THREAD

**Issue by saipavan1223** [ioBroker/ioBroker.vis.cordova#1]
I'm using the latest LocalFileSystem.java and I'm getting null in for the data stored in SD card.How to overcome this.I tried using context.getExternalCacheDirs but still I'm getting the same error.Please help me.
<img width="604" alt="screen shot 2016-03-08 at 9 38 17 am" src="https://cloud.githubusercontent.com/assets/13970630/13610244/94519b1e-e511-11e5-9177-db3e8b5606d9.png">

**Comment by GermanBluefox** [comment]
The Problem is, my focus is not App development and I am rather new in this
material. As I can see it is cordova Java Plugin.
May be ask about it by cordova people?



2016-03-08 18:39 GMT+01:00 saipavan1223 <notifications@github.com>:

**Comment by saipavan1223** [comment]
okay thanks
