### ISSUE TITLE
not able to build app

### ISSUE THREAD

**Issue by rg-engineering** [ioBroker/ioBroker.vis.cordova#15]
I'm not able to build the app anymore. I pulled latest version into my local repository, cleaned up my working directory and startet with "npm install". I had to do it many times until all modules were available.
I had some trouble with "com.pylonproducts.wifiwizard" in dependencies of package.json. Finally I just removed that there. I'm not sure was it a good idea? 
For some reasons I had to install grunt and a couple of grunt-xxx packages manually. After that I was able to call "grunt build". Now I get 

>> Using this version of Cordova with older version of cordova-android is deprecated. Upgrade to 
>> cordova-android@5.0.0 or newer.
>> Error: Your android platform does not have Api.js
>>
>> Exited with code: 1.`

The strange thing is I have cordova V7.0.1 and cordova-android V6.3.0. But this seems not so important. More important is the missing js-file.

I guess api.js was removed in a earlier commit here?

**Comment by GermanBluefox** [comment]
Fixed. Please update

**Comment by rg-engineering** [comment]
thank you! it works.
But I had to remove "com.pylonproducts.wifiwizard" from package.json manually again.
I got
```
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/com.pylonproducts.wifiwizard
npm ERR! 404
npm ERR! 404  'com.pylonproducts.wifiwizard' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'iobroker.vis.cordova'
```
with "npm install"
After build process it appeared in package.json again...

**Comment by GermanBluefox** [comment]
You are right.
