### ISSUE TITLE
Cant show new Vis.Material design

### ISSUE THREAD

**Issue by Dome2075** [ioBroker/ioBroker.vis.cordova#34]
Hi,

i want to design my Vis wit the new [materialdesign.widgets](https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/master/README.md).
When i open my Vis in a Browser (Chrome) i can see my vis with embeded materialdesign widgets.
but when its opened by Vis.app the materialdesign widgets are not visible!?

whats wrong or is there someting missing in the code?

Thanks for help

Dome

**Comment by mrMuppet** [comment]
Thats really a big issue, because this materialdesign.widget is fantastic! Please fix.

**Comment by Frank1604** [comment]
Same problem here, the widgets are not shown. What can I do to display them?

**Comment by armintan** [comment]
Same problem here. Any indication if and when this will be working?

**Comment by mrMuppet** [comment]
BlueFox will integrate Material in Visapp when it's in stable.

**Comment by GermanBluefox** [comment]
Done
