### ISSUE TITLE
iOS App: (auto-)remove error message

### ISSUE THREAD

**Issue by Standarduser** [ioBroker/ioBroker.vis.cordova#46]
I would like to suggest following change on ioBroker VIS iOS app:

If connection is lost to server due to ioBroker restart there are shown 2 error messages. One seems to be web content and the other seems to be an iOS popup window.
![IMG_5DBA749CF8FB-1](https://user-images.githubusercontent.com/8029204/208077266-8fb865d4-3943-43aa-a767-98af9e905140.jpeg)

When the connection is established again, VIS gets fully new loaded and one error message has gone, but the other message stays in place until you push OK.
![IMG_A2E87F8C7772-1](https://user-images.githubusercontent.com/8029204/208077959-5f5906c4-da08-4605-b45a-c435bd5fd8a9.jpeg)

Please consider to auto-remove the iOS popup message or, if not possible, remove this message completely.
Thanx in advance

**Comment by TA2k** [comment]
The error is intended to show the user wrong url or in your case if the vis is not reachable under the url.
You should never see the error with a correct url or the vis is available and not restarting
